chore(database): Configure application to use Postgresql
andela/ivy-ah-backend pull request #3
Opened 2019-03-25 18:13 UTC by kayroy247

#### What does this PR do?
This PR configures Author's Haven to use Postgres as the database engine
#### Description of Task to be completed?
This task will be completed with the creation of databases on Heroku and using the connection URI in the connection string
#### How should this be manually tested?
This can be mannually tested by starting the app
#### Any background context you want to provide?
Author's Haven comes with the support for MongoDB but is now configured to use Postgresql
#### What are the relevant pivotal tracker stories?
#161780551
### Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/38121456/54943620-f7268780-4f31-11e9-97da-473fe74d6da9.png)

![image](https://user-images.githubusercontent.com/38121456/54943665-04dc0d00-4f32-11e9-87e7-b4a74693386a.png)

2019-03-26 10:05 UTC, fuchodeveloper commented on .env.sample
> +DATABASE_URL=
Add end of line

2019-03-26 10:06 UTC, fuchodeveloper commented on index.js
> +            console.log('Database connection successfull.');
Remove console log statements

2019-03-26 10:59 UTC, kayroy247 commented on .env.sample
> +DATABASE_URL=
Ok thanks. I will add it.

2019-03-26 13:14 UTC, kayroy247 commented on index.js
> +            console.log('Database connection successfull.');
Okay. I will do that.

2019-03-28 11:08 UTC, fuchodeveloper requested changes

2019-03-28 11:08 UTC, fuchodeveloper commented on src/index.js
> +    console.log(err.stack);
No console log statements in your pull requests

2019-03-29 12:10 UTC, fuchodeveloper requested changes
Resolve merge conflicts

2019-03-29 12:10 UTC, fuchodeveloper commented on src/index.js
> +    console.log(err.stack);
Remove log statements

2019-03-29 12:21 UTC, fuchodeveloper reviewed
gitignore the `.DS_Store` file. It should not be added to the repo

2019-03-29 14:04 UTC, Joyce-O commented
LGTM

2019-03-29 15:52 UTC, fuchodeveloper approved these changes

2019-03-29 15:54 UTC, merged